version: "3"
networks:
  default:
    external:
      name: kong-network

services:
  redis:
    image: redis:7
    restart: always
    environment:
      TZ: Asia/Bangkok
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./redisinsight/database:/db
    ports:
      - 18001:8001
